use_frameworks!

platform :ios, '10.0'

target 'SwiftUIXPod_Example' do
  pod 'SwiftUIXPod', :path => '../'

  target 'SwiftUIXPod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
